MstoreReel/src/Entity/Chat.php
<?php

namespace App\Entity;

use App\Repository\ChatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChatRepository::class)
 */
class Chat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $channel;


    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $discussion = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(): ?int
    {
        return $this->id;
    }
    public function getChannel(): ?string
    {
        return $this->channel;
    }

    public function setChannel(string $channel): self
    {
        $this->channel = $channel;

        return $this;
    }


    public function getDiscussion(): ?array
    {
        return $this->discussion;
    }

    public function setDiscussion(?array $discussion): self
    {
        $this->discussion = $discussion;

        return $this;
    }
}

MstoreReel/src/Entity/Personne.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;






/**
 * Personne
 * @ORM\Table(name="personne", uniqueConstraints={@ORM\UniqueConstraint(name="email", columns={"email"}), @ORM\UniqueConstraint(name="username", columns={"username"})})
 * @ORM\Entity(repositoryClass=PersonneRepository::class)
 * @UniqueEntity(
 * fields= {"email"},
 * message="L'email que vous avez indiqué est déjà utilisé !"
 * )
 * * @UniqueEntity(
 * fields= {"username"},
 * message="Le Nom d'utilisateur que vous avez indiqué est déjà utilisé !"
 * )
 * @ORM\Entity
 */
class Personne implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=30, nullable=false)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=30, nullable=false)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="role", type="string", length=30, nullable=false)
     */
    private $role;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=250, nullable=false)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=100, nullable=false)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=100, nullable=false)
     * @Assert\Length(min="6" , minMessage="Votre mot de passe doit faire minimum 6 caractéres")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please upload image")
     * @Assert\File(mimeTypes={"image/jpeg"})
     */
    private $photo ;

    /**
     * @var string
     *
     * @ORM\Column(name="num_telephone", type="string", length=8, nullable=false)
     */
    private $numTelephone;


    public function construct()
    {

        $this->nom = new ArrayCollection();
        $this->prenom = new ArrayCollection();
        $this->role = new ArrayCollection();
        $this->email = new ArrayCollection();;
        $this->username = new ArrayCollection();
        $this->password = new ArrayCollection();
        $this->photo = new ArrayCollection();
        $this->numTelephone = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom(string $nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return string
     */
    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    /**
     * @param string $prenom
     */
    public function setPrenom(string $prenom): void
    {
        $this->prenom = $prenom;
    }

    /**
     * @return string
     */
    public function getRole(): ?string
    {
        return $this->role;
    }

    /**
     * @param string $role
     */
    public function setRole(string $role): void
    {
        $this->role = $role;
    }

    /**
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @param string $username
     */
    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    /**
     * @return string
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * @param mixed $image
     */
    public function setPhoto($photo): void
    {
        $this->photo = $photo;
    }

    /**
     * @return string
     */
    public function getNumTelephone(): ?string
    {
        return $this->numTelephone;
    }

    /**
     * @param string $numTelephone
     */
    public function setNumTelephone(string $numTelephone): void
    {
        $this->numTelephone = $numTelephone;
    }
    /**
     *@Assert\EqualTo(propertyPath="password" , message="Vous n'avez pas tapez la même mot de passe")
     */
    public $confirm_password;

    public function getRoles()
    {
        return ['ROLE_USER'];
    }
    public function getSalt()
    {

    }
    public function eraseCredentials()
    {

    } /*
    public function serialize()
    {
        return serialize([
            $this->id,

            $this->username,

            $this->numTelephone,
            $this->prenom,
            $this->nom,
            $this->photo,
            $this->role,
            $this->email,
            $this->password
        ]);
    }
    public function unserialize($string)
{
List (

$this->id,

$this->username,

$this->numTelephone,
$this->prenom,
$this->nom,
$this->photo,
$this->role,
$this->email,
$this->password
) = unserialize(string ,['allowed_classes' => false]);
}

*/
}

MstoreReel/src/Controller/ChatController.php
<?php

namespace App\Controller;

use App\Entity\Chat;
use Doctrine\DBAL\Query\QueryException;
use Pusher\Pusher;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChatController extends AbstractController
{
    /**
     * @Route("/chat", name="chat")
     */
    public function index(): Response
    {
        $user = $this->getUser();
        $idChannel = $user ->getRole()[0] . '_channel';



        $query = $this->getDoctrine()->getManager()->createQuery("SELECT c FROM App\Entity\Chat c WHERE c.channel = :channel")->setMaxResults(1);
        $query->setParameter('channel', $idChannel);
        $chat = $query->getOneOrNullResult();

        // no result or non unique result

        if($chat == null){
            $chat= new Chat();
            $chat->setChannel($idChannel);
            $chat->setDiscussion([]);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($chat);
            $entityManager->flush();
        }


        //$discussion=$chat->getDiscussion();

        $discussion = $chat->getDiscussion();

        return $this->render('chat/index.html.twig', [
            'discussion' => $discussion,
            'pusherKey' => $this->getParameter('pusherKey'),
            'pusherCluster' => $this->getParameter('pusherCluster'),
        ]); 

        
    }


    /**
     * @Route("/chatt", name="demo_chat", methods={"POST"})
     */
    public function indexPusher(Request $request, Pusher $pusher): Response
    {

        //$chat_message = json_decode($request->getContent(), true)['chat_message'];
        //$chat_message['message'];
        $user = $this->getUser();
        $idChannel = $user ->getRoles()[0] . '_channel';
        $idEvent = $user ->getRoles()[0] . '_event';
        $data = $request->get('message');


        $query = $this->getDoctrine()->getManager()->createQuery("SELECT c FROM App\Entity\Chat c WHERE c.channel = :channel")->setMaxResults(1);
        $query->setParameter('channel', $idChannel);

            // default action is always to return a Document
            $chat = $query->getOneOrNullResult();

            // no result or non unique result
            if($chat == null){
                $chat= new Chat();
                $chat->setChannel($idChannel);
                $chat->setDiscussion([]);
            }

            
            $discussion=$chat->getDiscussion();
            array_push($discussion,$data);
            $chat->setDiscussion($discussion);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($chat);
            $entityManager->flush();


            if($pusher->trigger($idChannel, $idEvent, $data)) {

                

                echo 'success';
            
            } else {
            
                echo 'error';
            
            }


        return new Response();

    }



}

MstoreReel/templates/chat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chat{% endblock %}

{% block body %}
<header class="masthead">
    <div class="container">

    <style = "text/css">
        .messages_display {height: 300px; overflow: auto;}
        .messages_display .message_item {padding: 0; margin: 0; }
        .bg-danger {padding: 10px;}

    </style>
    </head>

    <br>

    <!--Form Start-->
    <div class = "container">

        <div class = "col-md-6 col-md-offset-3 chat_box" id="chatbox">
            <div> <h1> Votre discussion </h1></div>
            <div class="-italic"> Valable jusqu'à la première actualisation de la page </div>
            <br/>
            <div class = "form-control messages_display"></div>
            <br />
            <div class = "form-group">
                <textarea class = "input_message form-control" placeholder = "Enter Message" rows="5"></textarea>
            </div>
            <div class = "form-group input_send_holder">
                <input type = "submit" value = "Send" class = "btn btn-primary btn-block input_send" id="SENDER"/>
            </div>
        </div>

        <!--form end-->




    </div>
    </div>
</header>
{% endblock %}


{% block javascripts %}
    {{ parent() }}

    <script type="text/javascript">

        console.log("COME ON")


        $( document ).ready(function() {

            console.log("YOU HOO")
            var d = new Array();

            {% for disc in discussion %}
            d.push('{{ disc }}'); //Fill up the total queue

            {% endfor %}

            d.map(data=>{
                console.log("my_data to display",data);
                console.log("my_data to display",data);
                $('.messages_display').append('<p class = "message_item">' + data + '</p>');
            })
            $('.input_send_holder').html('<input type = "submit" value = "Send" class = "btn btn-primary btn-block input_send" />');
            $(".messages_display").scrollTop($(".messages_display")[0].scrollHeight);


        });

        // Add API Key & cluster here to make the connection
        var pusher = new Pusher("{{ pusherKey }}", {
            cluster: "{{ pusherCluster }}",
        });


        // Enter a unique channel you wish your users to be subscribed in.
        var channel = pusher.subscribe('{{ app.user.roles[0] }}'+'_channel');

        // bind the server event to get the response data and append it to the message div
        channel.bind('{{ app.user.roles[0] }}'+'_event',
            function(data) {
                console.log("my_data to display",data);
                $('.messages_display').append('<p class = "message_item">' + data + '</p>');
                $('.input_send_holder').html('<input type = "submit" value = "Send" class = "btn btn-primary btn-block input_send" />');
                $(".messages_display").scrollTop($(".messages_display")[0].scrollHeight);
            });

        // check if the user is subscribed to the above channel
        channel.bind('pusher:subscription_succeeded', function(members) {
            console.log('successfully subscribed!');
        });

        // Send AJAX request to the PHP file on server
        function ajaxCall(ajax_url, ajax_data) {
            $.ajax({
                type: "POST",
                url: ajax_url,
                //dataType: "json",
                data: ajax_data,
                success: function(response) {
                    console.log(response);
                },
                error: function(msg) {}
            });
        }

        // Trigger for the Enter key when clicked.
        $.fn.enterKey = function(fnc) {
            return this.each(function() {
                $(this).keypress(function(ev) {
                    var keycode = (ev.keyCode ? ev.keyCode : ev.which);
                    if (keycode == '13') {
                        fnc.call(this, ev);
                    }
                });
            });
        }

        // Send the Message enter by User
        $('body').on('click', '.chat_box .input_send', function(e) {
            console.log("from Senddsdsddd")
            e.preventDefault();

            var msg = $('.chat_box .input_message').val();
            var name = "{{app.user.username}}"

            // Validate Name field
            if (name === '') {
                bootbox.alert('<br /><p class = "bg-danger">Please enter a Name.</p>');
            }

            else if (msg !== '') {
                // Define ajax data
                var chat_message = {
                    name: name,
                    msg: msg,
                    message: name + ':  ' + msg
                }
                //console.log(chat_message);
                // Send the message to the server passing File Url and chat person name & message
                ajaxCall("{{ path('demo_chat') }}", chat_message);

                // Clear the message input field
                $('.chat_box .input_message').val('');
                // Show a loading image while sending
                $('.input_send_holder').html('<input type = "submit" value = "Send" class = "btn btn-primary btn-block" disabled /> &nbsp;<img     src = "loading.gif" />');
            }
        });

        // Send the message when enter key is clicked
        $('.chat_box .input_message').enterKey(function(e) {
            e.preventDefault();
            $('.chat_box .input_send').click();
        });


    </script>



{% endblock %}